name: ThiemesPresents
main: nl.thieme.tp.ThiemesPresents
version: 1.1
api-version: 1.13
authors: [ ThiemeH ]
softdepend: [ Essentials ]
description: Presents for everyone!
commands:
  thiemespresents:
    description: Main command
    aliases: [ present, presents ]